"""Fast render-level tests for the production Library archetype.

Real `uv build`/wheel/import checks live in the slow ``archetype``-marked
``tests/test_library_build.py`` instead -- see docs/library-archetype.md.
"""

from __future__ import annotations

import tomllib

import pytest

from forge_template import (
    ComponentOwner,
    FoundationOwner,
    discover_components,
    map_legacy_library_answers,
    parse_project_spec,
    plan_generation,
    render_project,
)

_PACKAGING_MODES = ("uv-build-static", "hatchling-static", "hatchling-vcs")


def _payload(
    *, packaging_mode: str, initial_version: str = "0.1.0"
) -> dict[str, object]:
    return {
        "protocol_version": 1,
        "project": {
            "name": "Credit Risk Utils",
            "package_name": "credit_risk_utils",
            "repository_name": "credit-risk-utils",
            "description": "Shared credit-risk calculations.",
            "licence": "mit",
            "authors": [{"name": "Test User", "email": "test@example.invalid"}],
        },
        "python": {"minimum": "3.11", "development": "3.13"},
        "components": {"archetype": "library", "capabilities": [], "platforms": []},
        "component_options": {
            "library": {
                "packaging_mode": packaging_mode,
                "initial_version": initial_version,
            }
        },
    }


def test_discovery_exposes_library_with_cli_and_capabilities() -> None:
    descriptors = discover_components()
    assert [descriptor.id for descriptor in descriptors] == [
        "cli",
        "data-science",
        "jupyter",
        "library",
        "scientific-python",
    ]

    library = next(d for d in descriptors if d.id == "library")
    assert library.kind == "archetype"
    assert library.version == "1.0.1"
    assert library.requires == ()
    assert library.conflicts == ()

    packaging_mode = next(o for o in library.options if o.name == "packaging_mode")
    assert packaging_mode.required is False
    assert packaging_mode.default == "uv-build-static"
    assert set(packaging_mode.choices) == {
        "uv-build-static",
        "hatchling-static",
        "hatchling-vcs",
    }

    initial_version = next(o for o in library.options if o.name == "initial_version")
    assert initial_version.default == "0.1.0"
    assert initial_version.format == "pep440"


@pytest.mark.parametrize("packaging_mode", _PACKAGING_MODES)
def test_plan_identifies_foundation_and_component_owners(packaging_mode: str) -> None:
    spec = parse_project_spec(_payload(packaging_mode=packaging_mode))

    plan = plan_generation(spec)

    assert plan.component_order == ("library",)
    by_target = {item.target: item for item in plan.files}

    assert by_target["pyproject.toml"].owner == FoundationOwner()
    assert by_target["README.md"].owner == FoundationOwner()
    assert by_target["LICENSE"].owner == FoundationOwner()
    assert by_target["CONTRIBUTING.md"].owner == FoundationOwner()
    assert by_target["SECURITY.md"].owner == FoundationOwner()
    assert by_target[".gitignore"].owner == FoundationOwner()
    assert by_target[".gitattributes"].owner == FoundationOwner()
    assert by_target[".editorconfig"].owner == FoundationOwner()
    assert by_target[".python-version"].owner == FoundationOwner()

    assert by_target["src/credit_risk_utils/__init__.py"].owner == ComponentOwner(
        id="library"
    )
    assert by_target["src/credit_risk_utils/py.typed"].owner == ComponentOwner(
        id="library"
    )
    assert by_target["tests/__init__.py"].owner == ComponentOwner(id="library")
    assert by_target["tests/test_smoke.py"].owner == ComponentOwner(id="library")

    extensions = by_target["pyproject.toml"].extensions
    assert {e.extension_point for e in extensions} == {
        "pyproject-build-system",
        "pyproject-archetype-metadata",
        "pyproject-build-configuration",
        "pyproject-classifiers",
    }
    assert all(e.component_id == "library" for e in extensions)

    # _version.py is generated by hatch-vcs at build time (uv build), never
    # by the engine's own render step -- not part of the plan in any mode.
    assert "src/credit_risk_utils/_version.py" not in by_target


@pytest.mark.parametrize("packaging_mode", _PACKAGING_MODES)
def test_rendered_pyproject_is_valid_toml_per_packaging_mode(
    packaging_mode: str,
) -> None:
    spec = parse_project_spec(
        _payload(packaging_mode=packaging_mode, initial_version="0.4.2")
    )

    rendered = render_project(spec)
    files = {item.target: item.content for item in rendered.files}

    payload = tomllib.loads(files["pyproject.toml"].decode())
    assert payload["project"]["name"] == "credit-risk-utils"
    assert payload["project"]["requires-python"] == ">=3.11"
    assert payload["project"]["license"] == "MIT"

    if packaging_mode == "uv-build-static":
        assert payload["project"]["version"] == "0.4.2"
        assert payload["build-system"]["build-backend"] == "uv_build"
        assert (
            payload["tool"]["uv"]["build-backend"]["module-name"] == "credit_risk_utils"
        )
    elif packaging_mode == "hatchling-static":
        assert payload["project"]["version"] == "0.4.2"
        assert payload["build-system"]["build-backend"] == "hatchling.build"
        assert payload["tool"]["hatch"]["build"]["targets"]["wheel"]["packages"] == [
            "src/credit_risk_utils"
        ]
        assert "version" not in payload.get("tool", {}).get("hatch", {})
    else:
        assert payload["project"]["dynamic"] == ["version"]
        assert "version" not in payload["project"]
        assert payload["build-system"]["requires"] == ["hatchling", "hatch-vcs"]
        assert payload["tool"]["hatch"]["version"]["source"] == "vcs"


def test_neutral_extension_points_preserve_library_output() -> None:
    """The reviewed neutral points preserve the Library contract.

    Library must keep publishing an empty dependency array, its owned typed
    classifier, and no ``[project.scripts]`` table -- structural
    evidence (not byte-for-byte, since an empty extension marker line is
    consumed along with its own newline) that those points leave Library's
    own output unchanged. See docs/cli-application-archetype.md.
    """
    spec = parse_project_spec(_payload(packaging_mode="uv-build-static"))

    rendered = render_project(spec)
    files = {item.target: item.content for item in rendered.files}
    payload = tomllib.loads(files["pyproject.toml"].decode())

    assert payload["project"]["dependencies"] == []
    assert payload["project"]["classifiers"] == ["Typing :: Typed"]
    assert "scripts" not in payload["project"]


def test_composed_file_set_matches_the_expected_project_shape() -> None:
    spec = parse_project_spec(_payload(packaging_mode="uv-build-static"))

    rendered = render_project(spec)
    targets = {item.target for item in rendered.files}

    assert targets == {
        "pyproject.toml",
        "README.md",
        "LICENSE",
        "CONTRIBUTING.md",
        "SECURITY.md",
        ".gitignore",
        ".gitattributes",
        ".editorconfig",
        ".python-version",
        "src/credit_risk_utils/__init__.py",
        "src/credit_risk_utils/py.typed",
        "tests/__init__.py",
        "tests/test_smoke.py",
    }


def test_gitignore_only_excludes_generated_version_file_in_vcs_mode() -> None:
    static_spec = parse_project_spec(_payload(packaging_mode="uv-build-static"))
    vcs_spec = parse_project_spec(_payload(packaging_mode="hatchling-vcs"))

    static_gitignore = next(
        item.content
        for item in render_project(static_spec).files
        if item.target == ".gitignore"
    ).decode()
    vcs_gitignore = next(
        item.content
        for item in render_project(vcs_spec).files
        if item.target == ".gitignore"
    ).decode()

    assert "credit_risk_utils/_version.py" not in static_gitignore
    assert "credit_risk_utils/_version.py" in vcs_gitignore


def test_smoke_test_imports_the_rendered_package() -> None:
    spec = parse_project_spec(_payload(packaging_mode="uv-build-static"))

    rendered = render_project(spec)
    smoke_test = next(
        item.content for item in rendered.files if item.target == "tests/test_smoke.py"
    ).decode()

    assert "from credit_risk_utils import __version__" in smoke_test


# --- map_legacy_library_answers against the real production schema ---------


@pytest.mark.parametrize(
    ("build_backend", "versioning_resolved", "packaging_mode"),
    [
        ("uv_build", "static", "uv-build-static"),
        ("hatchling", "static", "hatchling-static"),
        ("hatchling", "vcs", "hatchling-vcs"),
    ],
)
def test_legacy_mapping_rows_are_valid_choices_on_the_real_schema(
    build_backend: str, versioning_resolved: str, packaging_mode: str
) -> None:
    result = map_legacy_library_answers(
        {"build_backend": build_backend, "versioning_resolved": versioning_resolved}
    )
    assert result == {"packaging_mode": packaging_mode}

    library = next(d for d in discover_components() if d.id == "library")
    schema_choices = next(
        o.choices for o in library.options if o.name == "packaging_mode"
    )
    assert result["packaging_mode"] in schema_choices
