"""The supported Forge template-engine API and repository tooling.

Nothing in this package is copied into generated projects. Public engine
clients should import the names re-exported here rather than reaching into
the low-level composition modules directly.
"""

from forge_template.engine import (
    SUPPORTED_COMPONENT_MANIFEST_PROTOCOLS,
    SUPPORTED_PROJECTSPEC_PROTOCOLS,
    ComponentDescriptor,
    ComponentOption,
    ComponentRelation,
    EngineErrorCode,
    EngineErrorDetail,
    EngineInfo,
    ForgeEngineError,
    GenerationPlan,
    PlannedExtension,
    PlannedFile,
    RenderedFile,
    RenderedProject,
    discover_components,
    get_engine_info,
    map_legacy_library_answers,
    parse_generation_metadata,
    parse_project_spec,
    plan_generation,
    plan_update,
    render_project,
    validate_project_spec,
    validate_rendered_project,
    verify_generation_metadata,
)
from forge_template.file_conflicts import ComponentOwner, FoundationOwner
from forge_template.generation_metadata import (
    DEFAULT_GENERATION_METADATA_TARGET,
    GENERATION_METADATA_VERSION,
    AppliedRename,
    GenerationMetadata,
    MetadataProtocols,
    OutputRecord,
    ProviderIdentity,
    ReproductionRecord,
    SelectedComponent,
    UpdatePlan,
    UpdateTarget,
)
from forge_template.project_spec import (
    PROJECT_SPEC_PROTOCOL_VERSION,
    Author,
    ComponentSelection,
    ProjectMetadata,
    ProjectSpec,
    PythonSelection,
    SelectionProvenance,
)

__all__ = [
    "DEFAULT_GENERATION_METADATA_TARGET",
    "GENERATION_METADATA_VERSION",
    "PROJECT_SPEC_PROTOCOL_VERSION",
    "SUPPORTED_COMPONENT_MANIFEST_PROTOCOLS",
    "SUPPORTED_PROJECTSPEC_PROTOCOLS",
    "AppliedRename",
    "Author",
    "ComponentDescriptor",
    "ComponentOption",
    "ComponentOwner",
    "ComponentRelation",
    "ComponentSelection",
    "EngineErrorCode",
    "EngineErrorDetail",
    "EngineInfo",
    "ForgeEngineError",
    "FoundationOwner",
    "GenerationMetadata",
    "GenerationPlan",
    "MetadataProtocols",
    "OutputRecord",
    "PlannedExtension",
    "PlannedFile",
    "ProjectMetadata",
    "ProjectSpec",
    "ProviderIdentity",
    "PythonSelection",
    "RenderedFile",
    "RenderedProject",
    "ReproductionRecord",
    "SelectedComponent",
    "SelectionProvenance",
    "UpdatePlan",
    "UpdateTarget",
    "discover_components",
    "get_engine_info",
    "map_legacy_library_answers",
    "parse_generation_metadata",
    "parse_project_spec",
    "plan_generation",
    "plan_update",
    "render_project",
    "validate_project_spec",
    "validate_rendered_project",
    "verify_generation_metadata",
]
